"""changing resgistered_on to registered_on

Revision ID: 5dcc7d51b454
Revises: 
Create Date: 2022-03-22 08:05:02.128459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5dcc7d51b454'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registered_on', sa.DateTime(), nullable=False))
    op.drop_column('users', 'resgistered_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('resgistered_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('users', 'registered_on')
    # ### end Alembic commands ###
